(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f;if("function"==typeof Object.setPrototypeOf)f=Object.setPrototypeOf;else{var h;a:{var k={g:!0},l={};try{l.__proto__=k;h=l.g;break a}catch(a){}h=!1}f=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=f,p=this||self,q=function(a,b){function c(){}c.prototype=b.prototype;a.j=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.l=function(d,g,G){for(var w=Array(arguments.length-2),m=2;m<arguments.length;m++)w[m-2]=arguments[m];return b.prototype[g].apply(d,w)}};function r(a){if(Error.captureStackTrace)Error.captureStackTrace(this,r);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(r,Error);r.prototype.name="CustomError";var t=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,g=0;g<d;g++)c+=a[g]+(g<b.length?b[g]:"%s");r.call(this,c+a[d])};q(t,r);t.prototype.name="AssertionError";var u=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var g=Array.prototype.slice.call(arguments,2)}throw new t(""+d,g||[]);}return a},v=function(a,b){throw new t("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var x=function(a,b){var c=String(b).toLowerCase();a=String(a.substr(0,b.length)).toLowerCase();return 0==(c<a?-1:c==a?0:1)};var z=function(a,b){this.b=b===y?a:""};z.prototype.i=!0;z.prototype.h=function(){return this.b.toString()};z.prototype.toString=function(){return"SafeUrl{"+this.b+"}"};var A=function(a){var b=a.indexOf("#");0<b&&(a=a.substring(0,b));b=a.match(/[?&]body=/gi);if(!b)return!0;if(1<b.length)return!1;a=a.match(/[?&]body=([^&]*)/)[1];if(!a)return!0;try{decodeURIComponent(a)}catch(c){return!1}return/^(?:[a-z0-9\-_.~]|%[0-9a-f]{2})+$/i.test(a)},B=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,y={};var C=function(){var a=HTMLElement.call(this)||this;a.c=a.dial.bind(a);a.f=!1;return a},D=HTMLElement;C.prototype=e(D.prototype);C.prototype.constructor=C;if(n)n(C,D);else for(var E in D)if("prototype"!=E)if(Object.defineProperties){var F=Object.getOwnPropertyDescriptor(D,E);F&&Object.defineProperty(C,E,F)}else C[E]=D[E];C.j=D.prototype;
C.prototype.connectedCallback=function(){if(!this.f){for(this.a=this.ownerDocument.createElement("gwd-taparea");this.children.length;)this.a.appendChild(this.firstChild);this.appendChild(this.a);this.f=!0}this.a.addEventListener("action",this.c)};C.prototype.disconnectedCallback=function(){this.a.removeEventListener("action",this.c,!1)};
C.prototype.dial=function(){var a=this.getAttribute("number")||"",b=decodeURI(a)!==decodeURIComponent(a)?a:encodeURIComponent(a);a=this.hasAttribute("action")&&"sms"===this.getAttribute("action").toLowerCase()?"sms":"tel";b=a+":"+b;var c={url:b};c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent("taptocall",!0,!0,c);this.dispatchEvent(d);d.detail.handled||("tel"===a?(a=b,x(a,"tel:")||(a="about:invalid#zClosurez"),a=new z(a,y)):(a=b,x(a,"sms:")&&A(a)||(a="about:invalid#zClosurez"),
a=new z(a,y)),a instanceof z||a instanceof z||(a="object"==typeof a&&a.i?a.h():String(a),u(B.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new z(a,y)),b=a,a=p.open,b instanceof z&&b.constructor===z?b=b.b:(c=typeof b,v("expected object of type SafeUrl, got '"+b+"' of type "+("object"!=c?c:b?Array.isArray(b)?"array":c:"null")),b="type_error:SafeUrl"),a.call(p,b,""))};customElements.define("gwd-taptocall",C);}).call(this);
